# Generated by Django 5.0.6 on 2024-07-10 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('tiempo', models.CharField(max_length=255)),
                ('ubicacion', models.CharField(max_length=255)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_nino', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dificultad', models.CharField(max_length=255)),
                ('jornada', models.CharField(max_length=255)),
                ('imagen', models.CharField(max_length=255)),
                ('tour_desde', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Tour',
                'verbose_name_plural': 'Tours',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_turista', models.CharField(max_length=255)),
                ('rut_turista', models.CharField(max_length=12)),
                ('fecha_tour', models.DateField()),
                ('cantidad_adultos', models.IntegerField()),
                ('cantidad_ninos', models.IntegerField()),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.tour')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
            },
        ),
        migrations.CreateModel(
            name='Itinerario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField()),
                ('hora_final', models.TimeField()),
                ('actividad', models.CharField(default='Actividad', max_length=255)),
                ('detalle_actividad', models.TextField()),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.tour')),
            ],
            options={
                'verbose_name': 'Itinerario',
                'verbose_name_plural': 'Itinerarios',
            },
        ),
        migrations.CreateModel(
            name='TourDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField()),
                ('tipo_actividad', models.TextField()),
                ('nombre_base_imagen', models.CharField(max_length=50)),
                ('extensionimagenes', models.TextField()),
                ('descripcion', models.TextField()),
                ('url_mapa', models.CharField(max_length=600)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.tour')),
            ],
            options={
                'verbose_name': 'Detalle del Tour',
                'verbose_name_plural': 'Detalles del Tour',
            },
        ),
    ]
