# Generated by Django 5.0.6 on 2024-07-11 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_tourdetalle_options'),
    ]
