# Generated by Django 5.0.6 on 2024-07-11 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_reserva_ciudad_recogida_reserva_direccion_recogida'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='ciudad_recogida',
            field=models.TextField(default='Ciudad recogida'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='direccion_recogida',
            field=models.CharField(default='Ciudad recogida', max_length=255),
        ),
    ]
