# Generated by Django 5.0.6 on 2024-07-19 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_reserva_ciudad_recogida_reserva_direccion_recogida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='imagen',
            field=models.ImageField(upload_to='tours/images/'),
        ),
    ]
