# Generated by Django 5.0.6 on 2024-07-20 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_reserva_email_turista_alter_tour_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='email_turista',
            field=models.EmailField(default='ejemplo@ejemplo.cl', max_length=254),
        ),
    ]
