# Generated by Django 5.0.6 on 2024-07-20 02:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_reserva_email_turista'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={},
        ),]