# Generated by Django 5.0.6 on 2024-07-20 05:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_reserva_options_remove_reserva_tour_and_more'),
    ]
