# Generated by Django 5.0.6 on 2024-07-20 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_alter_itinerario_options_remove_reserva_tour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourdetalle',
            name='tour',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainapp.tour'),
        ),
    ]
